### ISSUE TITLE
Registrar la Especificación de Requerimientos mediante la documentación IEEE830 (subirlo en una carpeta de GitHub en la rama main).

### ISSUE THREAD

**Issue by jesicaortiz** [jesicaortiz/Proyecto-FullStack#1]

**Comment by TrianaDevia** [comment]
[RequisitosIEEE830.docx](https://github.com/jesicaortiz/Proyecto-FullStack/files/9692955/RequisitosIEEE830.docx)

**Comment by jesicaortiz** [comment]
![Image](https://user-images.githubusercontent.com/83972686/193469616-e2e79f5a-4434-4cbd-b332-9784fa3f2f90.jpg)

**Comment by jesicaortiz** [comment]
Éste en formato PNG

![Image](https://user-images.githubusercontent.com/83972686/193469669-ca661e2c-227c-49fc-bf27-94a39b8db788.png)

**Comment by TrianaDevia** [comment]
[RequisitosIEEE830 (2).docx](https://github.com/jesicaortiz/Proyecto-FullStack/files/9734363/RequisitosIEEE830.2.docx)
Adjunto requisitos con algunas modificaciones. Usar este ultimo para el Borrador IEEE830. Gracias

**Comment by jesicaortiz** [comment]
**Este es el diagrama definitivo que se va a usar para añadir al IEEE**

![Image](https://user-images.githubusercontent.com/83972686/194637092-aafefc8d-1c59-4456-9a43-db5b7871a721.png)
