### ISSUE TITLE
Historia de Usuarios y Tareas dependientes de las mismas

### ISSUE THREAD

**Issue by jesicaortiz** [jesicaortiz/Proyecto-FullStack#3]
-Plantear Historias de Usuarios y Tareas dependientes de las US para incorporarlas en el repositorio remoto GitHub. (Issues y Milestones) 
- Definir tareas dentro de las Historias de Usuario (GITHUB)

**Comment by TrianaDevia** [comment]
#US01: COMO desarrollador QUIERO crear la pagina web/aplicación que solicitó el cliente PARA satisfacer sus necesidades.
#TK01: Esquema de pagina web/aplicación con Figma u otro software de diseño.

**Comment by Ferramz** [comment]
US#1: Como usuario quiero una página web donde conseguir nuevos compañeros de partidas.
US#2: Como usuario quiero invitar a mis amigos para formar los equipos.
US#3: Como usuario quiero comprar distintas skins personalizadas.

**Comment by jesicaortiz** [comment]
#US01: Como desarrollador quiero diseñar una página web accesible para que pueda utilizarla cualquier usuario con algún tipo de  discapacidad.
#US02: Como desarrollador quiero diseñar una página web responsive para que se adapte a cualquier tipo de dispositivo.

**Comment by tuttiRoble** [comment]
HU1- Como desarrolladora quiero promover la comunidad GameMate con el fin de lograr la inclusion del trabajo femenino dentro del gaming
HU2- Como desarrolladora quiero promover la publicacion de eventos de videojuegos, esports de nuestra empresa
HU3- Como desarrolladora quiero ofrecer una pagina web con una reproducción del 100% de la gama de colores Adobe RGB

**Comment by AndreaGomezIT** [comment]
HU1-Como desarrolladora quiero crear una pagina con visibilidad, credibilidad y confiabilidad.
HU2- Como desarrolladora quiero que la pagina cuente con una excelente experiencia de usuario, con una interfaz amigable, logotipo y menú de navegación claros y un diseño intuitivo.
HU3-Como desarrolladora quiero que la pagina cuente con una tienda online, que tenga una buena estrategia de marketing, que sea compatible con CEO.

**Comment by AndreaGomezIT** [comment]
#US01: como usuario espero una pagina que sea fácilmente de comprender y navegar: con secciones claras y material actualizado
#US01: Como usuario espero que las actualizaciones no ralenticen ni perjudiquen la experiencia al navegar o al utilizar la app. 
#US01: Como usuario espero una pagina/app que  sea intuitiva y versátil,  sin publicidades excesivas.
#US01:

**Comment by Deboratayala** [comment]
#US01: Como usuario quiero tener una forma de como registrarme 

#TK01: Realizar un formulario de registro
#TK02: Crear una tabla de usuario en la Base de Datos 
#TK03: Crear el Backend necesario para agregar nuevos usuarios en la Base de Datos

----------------------------------------------------------------------------------------

#US02: Como usuario quiero tener una forma de modificar mi perfil
 
#TK01: Realizar Formulario  de perfil
#TK02: Crear el Backend necesario para modificar el usuario en la Base de Datos

**Comment by lucianovzqz** [comment]
#US01: Como usuario quiero un lugar seguro donde formar una comunidad

**Comment by Demaiowho** [comment]
#US01: Como usuario, QUIERO vender y registrar mis productos y cantidades que me soliciten PARA crear un pedido de venta.

#TK01: Crear sección tienda virtual y/o Carrito de compra.
