### ISSUE TITLE
idea de mapa del sitio

### ISSUE THREAD

**Issue by jesicaortiz** [jesicaortiz/Proyecto-FullStack#5]

**Comment by TrianaDevia** [comment]
![El texto del párrafo](https://user-images.githubusercontent.com/106435543/192162771-1b93d665-39c2-47b0-b97f-a2d71e720971.png)

**Comment by Deboratayala** [comment]
![Mapa de sitio](https://user-images.githubusercontent.com/106562536/192667804-82672e0f-a1c9-4fd7-8856-c3c10df44e42.jpg)

**Comment by tuttiRoble** [comment]
![GAMEMATE](https://user-images.githubusercontent.com/106545161/192680567-1f751a2b-aae5-48d7-a954-b02207413bdb.png)

**Comment by Demaiowho** [comment]
![GM - mapa de sitio](https://user-images.githubusercontent.com/106437437/192684571-337f7eec-9aad-476d-96aa-e651c64abcc9.png)
