### ISSUE TITLE
Bocetos para Game Mate 🖊

### ISSUE THREAD

**Issue by jesicaortiz** [jesicaortiz/Proyecto-FullStack#6]

**Comment by TrianaDevia** [comment]
[Azul Oscuro y Púrpura Tecnología Audaz Aplicación Negocio Sitio Web (1).zip](https://github.com/jesicaortiz/Proyecto-FullStack/files/9667434/Azul.Oscuro.y.Purpura.Tecnologia.Audaz.Aplicacion.Negocio.Sitio.Web.1.zip)

**Comment by TrianaDevia** [comment]
![header_nav](https://user-images.githubusercontent.com/106435543/192898457-41aedb47-d795-40f7-af9b-3ee28fadd2cf.png)
![banner](https://user-images.githubusercontent.com/106435543/192898483-7528423c-7957-4333-b14a-f7a1e4f66884.png)
![main_section1](https://user-images.githubusercontent.com/106435543/192898508-351b454b-4f4a-4862-979c-8b6ff60f0057.png)
![main_section2](https://user-images.githubusercontent.com/106435543/192898539-dd8fd228-763d-4a91-8f1f-ed2f28ffd4f7.png)
![footer](https://user-images.githubusercontent.com/106435543/192898558-07d9d159-9ec5-4778-9b83-3e97f30d37ac.png)
![empresa](https://user-images.githubusercontent.com/106435543/192898579-af6fa339-bd49-4c35-8ffc-5dc6700d9911.png)

**Comment by jesicaortiz** [comment]
https://www.figma.com/file/BIjmMII9NQu8KBwFpdWbuV/Game-Mate-project?node-id=0%3A1

**Comment by lucianovzqz** [comment]
https://www.figma.com/file/OZrHB7c2p6iH6w3FzFjgLW/boceto-de-pagina?node-id=0%3A1

**Comment by Deboratayala** [comment]
![Pagina de destino](https://user-images.githubusercontent.com/106562536/193426642-9697c8fc-2bf1-4bdb-9c0d-e4e31347a03e.png)
![Pagina de Crear cuenta](https://user-images.githubusercontent.com/106562536/193426645-382ae4ba-33c6-4c4f-8002-60a63cd9815e.png)
![Pagina de Inicio de Sesion](https://user-images.githubusercontent.com/106562536/193426646-806581fa-3efb-4361-bc23-724969c72b25.png)
![Pagina de Inicio](https://user-images.githubusercontent.com/106562536/193426647-d08362cb-6f42-436d-bc10-149ffea231a0.png)
![Pagina de Juego](https://user-images.githubusercontent.com/106562536/193426650-4fd5b625-fc02-4c07-bda1-9da623708618.png)
![Pagina dentro del juego](https://user-images.githubusercontent.com/106562536/193426653-330c6e26-081a-4759-9413-e356e6721296.png)
![Pagina de Nosotros](https://user-images.githubusercontent.com/106562536/193426655-7576c847-e4e1-41a4-bcde-638eea56ea69.png)
![Pagina de Mi perfil](https://user-images.githubusercontent.com/106562536/193426659-826f1128-d7c1-481d-8550-1235659e6bbf.png)
![Modal de Usuario](https://user-images.githubusercontent.com/106562536/193426662-f334cd1a-3203-4dd3-932f-5f4c75d0a28a.png)

**Comment by Deboratayala** [comment]
Falta cosas por agregar , como el logo y otros detalles , pero en general , se me ocurre que sea asi

**Comment by Deboratayala** [comment]
https://www.figma.com/file/pZPDi72CYCfqLFo5h8hOh7/Game-Mate?node-id=0%3A1
